FROM php:7.2-apache

RUN apt-get -y update && apt-get -y install libicu-dev libpng-dev libjpeg-dev libgif-dev vim libpq-dev libjpeg62-turbo-dev libmcrypt-dev \
&& docker-php-ext-install intl pdo pdo_pgsql pdo_mysql zip opcache mbstring iconv \
&& docker-php-ext-install pgsql \
&& docker-php-ext-install mcrypt \
&& docker-php-ext-install mbstring \
&& docker-php-ext-install exif \
&& docker-php-ext-configure gd --with-jpeg-dir=/usr/include/ \
&& docker-php-ext-install -j$(nproc) gd \
&& a2enmod rewrite \
&& curl -s http://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

#ENTRYPOINT ["docker-php-entrypoint"]
WORKDIR /var/www/html
EXPOSE 80
CMD ["apache2ctl", "-D", "FOREGROUND"]
#CMD ["apache2-foreground"]
