FROM php:7.2-apache

RUN apt-get -y update && apt-get -y install libicu-dev  libpng-dev libjpeg-dev libgif-dev vim libpq-dev \
&& docker-php-ext-install intl pdo pdo_pgsql pdo_mysql gd zip opcache mbstring iconv \
&& a2enmod rewrite \
&& curl -s http://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

#ENTRYPOINT ["docker-php-entrypoint"]
WORKDIR /var/www/html
EXPOSE 80
CMD ["apache2ctl", "-D", "FOREGROUND"]
#CMD ["apache2-foreground"]